import React from 'react';

const TermsAndConditions = () => {
    const containerStyle = {
        padding: '40px 20px',
        maxWidth: '1000px',
        margin: '0 auto',
        fontFamily: 'Arial, sans-serif',
        lineHeight: '1.6',
        color: '#fff'
    };

    const headingStyle = {
        marginBottom: '20px',
        fontSize: '2rem',
        fontWeight: 'bold'
    };

    const subHeadingStyle = {
        marginBottom: '15px',
        fontSize: '1.5rem',
        fontWeight: 'bold',
        marginTop: '30px'
    };

    const sectionStyle = {
        marginBottom: '30px'
    };

    const paragraphStyle = {
        marginBottom: '15px'
    };

    return (
        <div style={containerStyle}>
            <h1 style={headingStyle}>TERMS AND CONDITIONS</h1>
            <p style={paragraphStyle}><strong>Posted on:</strong> 12/01/2026</p>
            <p style={paragraphStyle}><strong>Effective from:</strong> 06/09/2025</p>

            <section style={sectionStyle}>
                <p style={{ ...paragraphStyle, fontWeight: 'bold' }}>
                    THIS DOCUMENT OF TERMS & CONDITIONS (“AGREEMENT”) IS AN ELECTRONIC RECORD IN THE FORM OF AN ELECTRONIC CONTRACT FORMED UNDER THE INFORMATION TECHNOLOGY ACT, 2000 AND THE RULES MADE THEREUNDER, AND THE AMENDED PROVISIONS PERTAINING TO ELECTRONIC DOCUMENTS/RECORDS IN VARIOUS STATUTES AS AMENDED FROM TIME TO TIME. THIS AGREEMENT DOES NOT REQUIRE ANY PHYSICAL, ELECTRONIC OR DIGITAL SIGNATURE.
                </p>
                <p style={{ ...paragraphStyle, fontWeight: 'bold' }}>
                    PLEASE READ THIS AGREEMENT CAREFULLY AS IT CONTAINS IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS; AND INCLUDES VARIOUS LIMITATIONS AND EXCLUSIONS, A CLAUSE THAT GOVERNS THE JURISDICTION AND VENUE OF DISPUTES, AND OBLIGATIONS TO COMPLY WITH APPLICABLE LAWS AND REGULATIONS.
                </p>
                <p style={paragraphStyle}>
                    This Agreement is a legally binding agreement between you (herein referred to as “you” or “your”) and Genrobotic Innovations Pvt Ltd (along with our affiliates and successors herein referred to as “we”, “us” or “our”).
                    Your access to or use of our products, services, applications, platform or websites is subject to and conditioned upon your acceptance of this Agreement as it is.
                </p>
                <p style={{ ...paragraphStyle, fontWeight: 'bold' }}>
                    BY CLICKING “I ACCEPT” OR “I AGREE” ON THE SIGNUP/LANDING PAGE, OR BY ACCESSING AND/OR USING OUR PRODUCTS, SERVICES, APPLICATIONS, PLATFORM OR WEBSITES IN ANY WAY, YOU AGREE TO BE BOUND BY THE TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE TO THE TERMS AND CONDITIONS OF THIS AGREEMENT IN FULL, THEN YOU SHOULD NOT USE OR OTHERWISE ACCESS OUR PRODUCTS, SERVICES, APPLICATIONS, PLATFORM OR WEBSITES; AND YOU MUST EXIT NOW.
                </p>
                <p style={paragraphStyle}>
                    This Agreement governs the access to and use of our products, services, applications, platform or websites. We may, in our sole and absolute discretion and without any specific notice to you, update and change any part or all of this Agreement, including but not limited to the terms associated with the access to or use of our products, services, applications, platform or websites. If we update or change this Agreement, then the updated version will be posted at https://genrobotics.com/ or on the relevant page of our products, services, applications, platform or websites. When we change/modify this Agreement, we will specify the ‘Last Modified’ / ‘Effective from’ date and the updated agreement will become effective and binding from such date. You are required to review this Agreement periodically/from time to time. Unless explicitly stated otherwise, any new features, services or products that change, augment or enhance our current products, services, applications, platform or websites shall be subject to the terms of this Agreement. Your access to and use of our products, services, applications, platform or websites is further subject to our Privacy Policy which is available on https://genrobotics.com/  and is incorporated herein by reference. Our products, services, applications, platform or websites may be subject to additional guidelines, terms or rules, etc. which will be posted on our respective products, services, applications, platform or websites and shall be deemed to be incorporated herein by reference.
                </p>
            </section>

            <section style={sectionStyle}>
                <h2 style={subHeadingStyle}>1 INFORMATION AND CORRECTION</h2>
                <p style={paragraphStyle}><strong>1.1</strong> All information available on our website regarding our products and services including the images of our products, is for illustrative purpose only. Our products are customizable and we offer different features/versions of our products and services, on the basis of customer requirements.</p>
                <p style={paragraphStyle}><strong>1.2</strong> Occasionally there may be information on our products, services, applications, platform or websites that contains errors, inaccuracies or omissions that may relate to product/service descriptions, specifications, illustrations, pricing, offers, and availability. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information.</p>
                <p style={paragraphStyle}><strong>1.3</strong> Certain products or services may be available exclusively through a specific channel such as ecommerce platform, resellers, distributors or third party portals.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={subHeadingStyle}>2 OUR PROPRIETARY RIGHTS</h2>
                <p style={paragraphStyle}><strong>2.1</strong> This is an agreement for access to and use of our products, services, applications, platform or websites, and save and except as provided herein, you are not granted any right, title, interest or license to any intellectual property rights under this Agreement. Our products, services, applications, platform and websites are based upon our proprietary technology, intellectual property and confidential information. Our products, services, applications, platform and websites are protected by applicable intellectual property and other laws, including patent, trademark, and copyright laws. Our products, services, applications, platform and websites, including all intellectual property rights therein, belongs to us or our licensors and are our or our licensors’ property.</p>
                <p style={paragraphStyle}><strong>2.2</strong> Our names, logos, brands and other marks used by us from time to time are our trademarks and property. The appearance, layout, color scheme, and design of our products, services, applications, platform or websites are protected trade dress. Save and except as provided herein, you do not receive any right or license to use the foregoing.</p>
                <p style={paragraphStyle}><strong>2.3</strong> We may enhance and/or modify any of our products, services, applications, platform or websites from time to time, in order to change them and/or change the user experience. Nothing in this Agreement shall prohibit us from making such enhancements and/or modifications to our products, services, applications, platform or websites.</p>
                <p style={paragraphStyle}><strong>2.4</strong> We may use and/or incorporate into our products, services, applications, platform or websites any suggestion or feedback provided by you, without any payment or restriction.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={subHeadingStyle}>3 USER DATA AND LICENSE</h2>
                <p style={paragraphStyle}><strong>3.1</strong> You may be permitted to upload, post, share or transmit or otherwise make available any User Data (as defined below). We assume that all User Data is of non-confidential and non-proprietary nature. You undertake not to upload, transmit or broadcast any User Data on or through our products, services, applications, platform or websites that you consider to be of confidential or proprietary nature.</p>
                <p style={paragraphStyle}><strong>3.2</strong> Subject to the provision of this Agreement, you shall own and retain all rights to the User Data. We do not claim exclusive ownership of the User Data that you provide to us including through our products, services, applications, platform or websites.</p>
                <p style={paragraphStyle}><strong>3.3</strong> Notwithstanding the foregoing, you hereby grant us a non-exclusive, worldwide, irrevocable, perpetual, unlimited, assignable, sub-licensable through single or multiple tiers, royalty-free and fully-paid license to: (i) copy, host, use, reproduce, modify, retitle, prepare derivative works of, improve, distribute, transmit, translate, paraphrase, excerpt, redact, publish, broadcast, archive, store, cache, remove, retain, add to, combine with information provided by third parties, and publicly display the User Data for any purpose, commercial, advertising or otherwise, including - (a) on, through or in respect of our products, services, applications, platform or websites; and/or (b) in our promotional and advertising materials; and/or (ii) sublicense to third parties such User Data to the extent necessary for the creation, operation and maintenance of, in part or in whole, our products, services, applications, platform or websites. You hereby also grant us, the perpetual and irrevocable right to delete any or all of the User Data from our products, services, applications, platform or websites, our servers/systems, whether intentionally or unintentionally, and for any reason or no reason, without any liability of any kind to you or any other person. No compensation will be paid to you with respect to our or our sub-licensee’s use of the User Data. You waive all moral rights in the User Data, and you warrant that the moral rights have not otherwise been asserted in the User Data.</p>
                <p style={paragraphStyle}><strong>3.4</strong> By submitting, posting, uploading, transmitting or otherwise making available any User Data or by posting messages, uploading files, inputting data, submitting any feedback or suggestions, or engaging in any other form of communication with or through our products, services, applications, platform or websites, you warrant and represent that you own or otherwise control the rights necessary to do so and to grant us the license set forth above. You represent and warrant that: (a) you have the right to post, submit and make available the User Data, and to grant the foregoing license; (b) the User Data is not false, inaccurate, or misleading; and (c) the User Data will not infringe, misappropriate or violate any third-party rights (including any intellectual property rights), or applicable laws.</p>
                <p style={paragraphStyle}><strong>3.5</strong> User Data is your data, and we are not responsible for the appropriateness, legality, integrity, accuracy, sufficiency, correctness, veracity, completeness, or timeliness of any such User Data. You acknowledge that we have no obligation to pre-screen, monitor, review, or edit any content (including User Data) submitted by you using our products, services, applications, platform or websites. You are solely responsible for the User Data, and you will defend, indemnify and hold us and our sub-licensees harmless from any third-party claim related to a breach of any of the foregoing obligations, representations and warranties. You expressly agree to exonerate us from any and all responsibility and to refrain from any legal action against us regarding the User Data.</p>
                <p style={paragraphStyle}><strong>3.6</strong> The terms “User Data” means any and all information and data submitted by you, including without limitation, texts, writings, videos, audios, photographs, graphics, comments, suggestions, or personal information or other material that you provide or post, upload, input or submit for public or private display.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={subHeadingStyle}>4 DATA MONITORING AND STORAGE</h2>
                <p style={paragraphStyle}><strong>4.1</strong> We are under no obligation, but do reserve the right in our sole discretion, to correct, pre-screen, filter, modify, intercept and analyze traffic of, copy, backup, redirect, transmit, refuse, limit access to, suspend, freeze, and remove any and all thoughts, opinions, and other User Data etc. We may also monitor the access to and use of our products, services, applications, platform or websites by any of our users in order to analyze the access to and use of our products, services, applications, platform or websites and/or improve our products, services, applications, platform or websites or to add features useful to our users.</p>
                <p style={paragraphStyle}><strong>4.2</strong> Furthermore, we may collect and use data related to such use, in an aggregate and anonymous manner, including compiling statistical and performance information related to the provision and operation of our products, services, applications, platform or websites. You agree that we may use and publish such aggregate and anonymous information. You consent that we may store, process and transmit information in locations around the world - including those outside your country. Information may also be stored locally on your devices that you may use to access or use our products, services, applications, platform or websites.</p>
                <p style={paragraphStyle}><strong>4.3</strong> The use and disclosure of data and information is further described in the Privacy Policy.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={subHeadingStyle}>5 REPRESENTATIONS, WARRANTIES AND COVENANTS</h2>
                <p style={paragraphStyle}><strong>5.1</strong> You represent, warrant, and covenant that: (a) you have the power and authority to enter into this Agreement; (b) you are a natural person and are at least eighteen (18) years of age; (c) you will only access and use our products, services, applications, platform or websites in accordance with the terms of this Agreement; and (d) you are and will at all times be, in full compliance with all applicable laws.</p>
                <p style={paragraphStyle}><strong>5.2</strong> In addition to other prohibitions as set forth in this Agreement, you are prohibited from accessing or using our products, services, applications, platform and/or websites: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, central, federal, provincial or state regulations, rules or laws; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will, or may be used in any way that will affect the functionality, or operation of our products, services, applications, platform or websites; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; (k) to interfere with or circumvent/bypass the security features of or restrictions on our products, services, applications, platform or websites; (l) to remove any logo, copyright or proprietary notices, disclaimer, legends, symbols, labels, watermarks, signatures or any other like marks affixed to or embedded therein; (m) to start a business (including reselling) or commercially exploit our products, services, applications, platform and/or websites; (n) to advertise or offer to sell goods and services; or (o) to post a review without firsthand experience.</p>
                <p style={paragraphStyle}><strong>5.3</strong> Access to or use of our products, services, applications, platform or websites may not be legal by certain persons or in certain states or countries or jurisdictions; and if you use or access our products, services, applications, platform or websites from outside India, you do so at your own risk and are responsible for compliance with the laws of India.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={subHeadingStyle}>6 THIRD-PARTY SITES</h2>
                <p style={paragraphStyle}><strong>6.1</strong> Third-Party Sites, if any, are not under our control, we have not investigated, monitored, or checked for accuracy, appropriateness or completeness of such Third-Party Sites, and we are not responsible in any manner whatsoever, for the contents of any Third-Party Site, including without limitation any link contained in a Third-Party Site, or any changes or updates to a Third-Party Site.</p>
                <p style={paragraphStyle}><strong>6.2</strong> We are not responsible for webcasting, or any other form of transmission received from or sent to any Third-Party Site. The Third-Party Sites are provided to you only as a convenience, and the inclusion of any Third-Party Site does not imply approval or endorsement by us of such Third-Party Site or our association with it. We are under no obligation, but do reserve the right in our sole discretion to pre-screen such Third Party Sites.</p>
                <p style={paragraphStyle}><strong>6.3</strong> Many Third-Party Sites have their own ‘terms of use’ ‘terms & conditions’ that differ from ours, and hence this Agreement only applies to our products, services, applications, platform or websites and do not apply to any other site or information, products, or services on such sites.</p>
                <p style={paragraphStyle}><strong>6.4</strong> The term “Third-Party Sites” means third-party websites linked-to or mentioned on our products, services, applications, platform or websites.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={subHeadingStyle}>7 INDEMNIFICATION</h2>
                <p style={paragraphStyle}>You agree to fully indemnify, defend and hold us and our suppliers, licensors, licensees, affiliates, partners, subsidiaries, employees, officers, directors, representatives, agents and members (each an “Indemnified Party”) harmless from and against any and all, direct or indirect, claims, demands, losses, liability, costs and expenses (including, but not limited to, attorneys’ fees and dispute resolutions costs) (collectively, “Liabilities”), incurred by an Indemnified Party arising out of or related to: (i) your breach of this Agreement including without limitation your breach of any representations, warranties or covenants; (ii) the creation, use, or maintenance of the User Data, including, without limitation, any allegation that any User Data or any other information or content provided by you infringes a third person’s copyright, trademark or other proprietary or intellectual property right, or misappropriates a third person's trade secrets or is unlawful, threatening, abusive, harassing, tortious, defamatory, obscene, harmful, libelous, invasive of another’s privacy, hateful, or racially or ethnically objectionable; (iii) any dispute or litigation between an Indemnified Party and a third party or any other third party claim caused by, arising from or relating to your actions or omissions in relation to this Agreement, our products, services, applications, platform or websites, any User Data; or (iv) your negligence or misconduct. These obligations will survive in perpetuity. To the fullest extent permitted by law, the foregoing indemnity will apply regardless of any fault, negligence, or breach of warranty or contract of or by us and/or our suppliers, licensors, licensees, affiliates, partners, subsidiaries, employees, officers, directors, representatives, agents and/or members.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={subHeadingStyle}>8 INJUNCTIVE RELIEF</h2>
                <p style={paragraphStyle}>You acknowledge that our products, services, applications, platform and websites contain valuable trade secrets and proprietary information of us and our other protected rights, and that any actual or threatened breach of this Agreement will constitute immediate, irreparable harm to us for which monetary damages would be an inadequate remedy, and hence injunctive relief is an appropriate remedy for such breach, which we shall be entitled to avail without any protest.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={subHeadingStyle}>9 DISCLAIMERS</h2>
                <p style={paragraphStyle}><strong>9.1</strong> We may send you newsletters and other information regarding our products, services, applications, platform or websites, links to other related websites and/or specific questions related to your data and preferences. The information contained in these communications and resources may be compiled from a variety of sources and may or may not be authentic or authored by us. Reliance on any information provided by us or through or on our products, services, applications, platform and websites or other users is solely at your own risk.</p>
                <p style={paragraphStyle}><strong>9.2</strong> We and our suppliers, licensors, licensees, affiliates, partners, subsidiaries, employees, officers, directors, representatives, agents and members make no warranty or covenant or representation and hereby expressly disclaim all warranties, covenants and representations, whether statutory or implied,: (i) that our products, services, applications, platform and websites and information and/or other material therein will meet your requirements or expectations or satisfaction levels; (ii) that our products, services, applications, platform and websites will be uninterrupted, timely, secure or error-free or that defects will be cured/corrected; (iii) regarding the suitability, reliability, accuracy, availability, completeness, validity or truthfulness of any information, material or other content obtained through use of or access to our products, services, applications, platform or websites; (iv) regarding merchantability, fitness for a particular purpose, title, non-infringement, errors, mistakes, inaccuracies of content and materials; or (iv) that any information, data, download, etc. available on or through hosting servers will be free of infection by viruses, worms, trojan horses, bugs, codes, hack, or anything else manifesting destructive properties.</p>
                <p style={paragraphStyle}><strong>9.3</strong> To the maximum extent permitted by applicable law, all such information, data, software, products, service and related material are provided by us on “as is”, “where is”, “as available”, “with all faults”, and “without recourse” basis without warranty or condition of any kind.</p>
                <p style={paragraphStyle}><strong>9.4</strong> No statement or information, whether oral or written, obtained from us by any means or in any fashion, shall create any warranty or representation.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={subHeadingStyle}>10 LIMITATIONS OF LIABILITY</h2>
                <p style={paragraphStyle}><strong>10.1</strong> In no event shall we or our suppliers, licensors, licensees, affiliates, partners, subsidiaries, employees, officers, directors, representatives, agents and members be liable for any direct, indirect, punitive, incidental, special, consequential, exemplary or other type of injury/losses/damages, including without limitation injury/losses/damages for loss of use, data, revenue or profits, arising out of or in any way connected with the use or performance of our products, services, applications, platform and websites, whether based on contract, tort, negligence, strict liability, the failure of any limited remedy to achieve its essential purpose, or otherwise, even if we or our suppliers, licensors, licensees, affiliates, partners, subsidiaries, employees, officers, directors, representatives, agents and members has/have been advised of the possibility of injury/losses/damages.</p>
                <p style={paragraphStyle}><strong>10.2</strong> We and our suppliers, licensors, licensees, affiliates, partners, subsidiaries, employees, officers, directors, representatives, agents and members are not liable or responsible for any injury or disease including aggravation, acceleration or recurrence of such injury or disease or death arising from or in connection with our products, services, applications, platform and/or websites.</p>
                <p style={paragraphStyle}><strong>10.3</strong> Notwithstanding the other terms of this Agreement and without prejudice to there being no liability of us and our suppliers, licensors, licensees, affiliates, partners, subsidiaries, employees, officers, directors, representatives, agents and members, if, at all, we or our suppliers, licensors, licensees, affiliates, partners, subsidiaries, employees, officers, directors, representatives, agents and members are determined to have any liability to you or to any third party under or pursuant to this Agreement for any loss, harm or damage, then you agree that our and our suppliers’, licensors’, licensees’, affiliates’, partners’, subsidiaries’, directors’, employees’, officers’, directors’, representatives’, agents’ and members’ total, cumulative, collective and aggregate liability shall in all cases be limited to INR 10,00,000/- (Indian Rupees Ten Lakhs only). The existence of more than one claim will not enlarge this limit on liability.</p>
                <p style={paragraphStyle}><strong>10.4</strong> You understand and agree that the foregoing limitation of liability is an agreed allocation of risk and an essential part of this Agreement. You understand and agree that without agreement to these limitation of liability provisions, we would not have provided our products, services, applications, platform and websites and would not have even entered into this Agreement with you.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={subHeadingStyle}>11 TERM, TERMINATION AND SUSPENSION</h2>
                <p style={paragraphStyle}><strong>11.1</strong> This Agreement shall remain in full force and effect while you use our products, services, applications, platform and/or websites.</p>
                <p style={paragraphStyle}><strong>11.2</strong> You may terminate your use or participation at any time, for any reason, by ceasing to use our products, services, applications, platform and websites and notifying us. The termination as against you shall not be effective till the time you have complied with all your obligations pursuant to this Agreement.</p>
                <p style={paragraphStyle}><strong>11.3</strong> We have the right to immediately terminate this Agreement or suspend your access to or use of our products, services, applications, platform and/or websites for any reason or no reason.</p>
                <p style={paragraphStyle}><strong>11.4</strong> We reserve the right, from time to time, to suspend or discontinue any products, services, applications, platform and/or websites, in whole or in part, with or without notice. You agree that we will not be liable to you or to any third party for any discontinuance or suspension of such products, services, applications, platform and/or websites, in whole or in part.</p>
                <p style={paragraphStyle}><strong>11.5</strong> All the previous data and information collected by us may be removed by us on termination or at any time, at our sole discretion.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={subHeadingStyle}>12 GENERAL</h2>
                <p style={paragraphStyle}><strong>12.1 Adequate Consideration:</strong> You agree that this Agreement is supported by reasonable and valuable consideration, the receipt and adequacy of which are hereby confirmed and acknowledged by you. Without limiting the foregoing, you acknowledge that such consideration includes your access to and/or use of our products, services, applications, platform and/or websites.</p>
                <p style={paragraphStyle}><strong>12.2 Entire Agreement:</strong> Unless otherwise expressly stated herein, this Agreement (read with any other agreement signed by us and our Privacy Policy) constitutes the entire agreement between you and us with respect to our products, services, applications, platform and websites; and supersedes all prior or contemporaneous communications, proposals and agreements, whether electronic, oral or written, between you and us with respect to the subject matter of this Agreement. We object to and reject any additional or different terms proposed by you. Our failure to object elsewhere to any provisions of any subsequent document, communication, or act put forth by you shall not be deemed a waiver of any of the terms hereof.</p>
                <p style={paragraphStyle}><strong>12.3 Assignment:</strong> You shall not assign or transfer this Agreement, in part or full, without our prior written consent. We may assign or transfer this Agreement, if full or in part, along with all rights and benefits to any successor or assigns or any other person without any notice to or consent from you.</p>
                <p style={paragraphStyle}><strong>12.4 Amendment:</strong> We may update and change any part or all of this Agreement, including but not limited to the product/service description, prices and charges associated with the access to or use of our products, services, applications, platform and/or websites, at our sole and absolute discretion.</p>
                <p style={paragraphStyle}><strong>12.5 No Waiver:</strong> No delay in exercising our rights or remedies will operate as a waiver of such right, or remedy, or any other right or remedy. A waiver on one occasion will not be construed as a waiver of any right or remedy on any future occasion.</p>
                <p style={paragraphStyle}><strong>12.6 Force Majeure:</strong> We shall not be responsible for failure or delay of performance if caused by: an act of war, hostility, or sabotage; act of God; electrical, internet or telecommunication outage; government restrictions (including lock-down); or any other event outside our or our service providers’ reasonable control.</p>
                <p style={paragraphStyle}><strong>12.7 Relationship:</strong> This Agreement, between you and us, is on a ‘principal to principal’ basis. You agree that no joint venture, partnership, employment or agency relationship exists between you and us as a result of this Agreement or by access to or use of our products, services, applications, platform and/or websites.</p>
                <p style={paragraphStyle}><strong>12.8 Feedback:</strong> By providing comments, creative ideas, suggestions, reviews, proposals, plans, and other feedback relating to our products, services, applications, platform and/or websites (collectively, “Feedback”) to us, you grant to us an irrevocable, perpetual, exclusive, royalty-free and fully paid, worldwide, transferable license, with the right to sublicense the right to edit, copy, publish, distribute, translate, use and exploit such Feedback, in any format or medium now known or developed in the future, for any purpose (commercial or otherwise,) and in any manner. We will have no obligation to give you any credit or compensate you in connection with any Feedback. We reserve the right to accept, reject, or remove the Feedback in our sole discretion.</p>
                <p style={paragraphStyle}><strong>12.9 Communication and Notices:</strong> The communications between you and us use electronic means, whether you use our products, services, applications, platform and/or websites or send us emails, or whether we post notices on our products, services, applications, platform and/or websites or communicate with you via email, for contractual purposes, you: (a) consent to receive communications from us in an electronic form; and (b) agree that all terms and conditions, agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement as if it were in hardcopy writing. Notice shall be sent to the contact address set forth here (as such may be changed by notice given to the other party) and shall be deemed delivered as of the date of actual receipt.
                    <br /><br />
                    To us: Addressing to the attention of Vipin MK who is designated as grievance officer at info@genrobotics.org or at our address provided on our website https://genrobotics.com/ .
                    <br /><br />
                    To you: As per the contact details provided to us at the time of registration or as may be updated from time to time in our records.
                    <br /><br />
                    We may give electronic notices to our user base by means of a general notice via our products, services, applications, platform and/or websites or may give electronic notices specific to you on e-mail addresses on record in our account information database. We may give telephonic notice to you by calls to appropriate numbers on record in our account information database. You hereby authorize us to send service-related transactional SMS/messages, even in the case that your contact number is listed as DND with the concerned telecom regulatory authority.
                </p>
                <p style={paragraphStyle}><strong>12.10 Language:</strong> This Agreement and all related documents be drawn up in English language and shall be interpreted only in English language.</p>
                <p style={paragraphStyle}><strong>12.11 Headings:</strong> The headings of sections/clauses included in this Agreement are inserted for convenience only and are not intended to affect the meaning or interpretation of this Agreement.</p>
                <p style={paragraphStyle}><strong>12.12 Independent Review:</strong> You acknowledge and agree to having read and fully understood the terms and conditions of this Agreement, and all related policies referenced and incorporated in this Agreement and agree to all its terms and conditions. You acknowledge and agree to have independently evaluated all aspects of this Agreement and the desirability of entering into the arrangement contemplated in this Agreement, and are not relying on any representation, warranty, guarantee or statement. In entering into this Agreement and accepting the terms and conditions set forth herein, you represent and warrant to have relied upon the legal advice of your attorneys/legal advisors. Notwithstanding the identity of the drafters of this Agreement, there will be no presumption for or against us or any other person arising out of or relating to the identity of such drafters.</p>
                <p style={paragraphStyle}><strong>12.13 Severability:</strong> If any part of this Agreement is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of this Agreement shall continue in effect.</p>
                <p style={paragraphStyle}><strong>12.14 Governing Law and Dispute Resolution:</strong> To the maximum extent permitted by law, this Agreement shall be governed by the laws of India without reference to conflicts of law principles; and, subject to the arbitration provision below, you hereby consent to the exclusive jurisdiction and venue of courts in Trivandrum (Kerala, India) in all disputes arising out of or relating to the access to or use of our products, services, applications, platform and/or websites or relating to this Agreement. Any dispute under this Agreement shall be referred for resolution by arbitration by a sole arbitrator appointed by us. Such arbitration shall be governed by the provisions of the Arbitration and Conciliation Act, 1996 and rules and ordinances thereto, as amended from time to time and shall be held at Trivandrum (Kerala, India). The arbitration shall be confidential, and you shall not disclose the existence, content or results of any arbitration, except as may be required by law or for purposes of enforcing the arbitration award. You hereby consent to waive to claim personal jurisdiction and venue in the above-referenced courts and agree not to challenge or object to such jurisdiction.</p>
                <p style={paragraphStyle}><strong>12.15 Survival:</strong> The provisions of this Agreement, which by its nature survives including without limitation Clauses pertaining to our proprietary rights, your indemnification obligations, your confidentiality obligations, our disclaimers, our limitations of liability and termination provisions shall survive expiry or termination of this Agreement.</p>
            </section>
        </div>
    );
};

export default TermsAndConditions;
